# Generated by Django 2.2 on 2019-05-08 04:09

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('accounts', '0002_userprofile_user'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.PositiveIntegerField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', tinymce.models.HTMLField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chap_number', models.PositiveIntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('overview', tinymce.models.HTMLField(blank=True, null=True)),
                ('act', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='stories.Act')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('genre', models.CharField(blank=True, choices=[('Action/Adventure', 'Action/Adventure'), ('Alt-History', 'Alternate History'), ('Anthology', 'Anthology'), ('Children', 'Children'), ('Classic', 'Classic'), ('Comic', 'Comic'), ('Coming-of-age', 'Coming of age'), ('Crime/detective', 'Crime/detective'), ('Drama', 'Drama'), ('Erotic', 'Erotic'), ('Fable', 'Fable'), ('Fan fiction', 'Fan fiction'), ('Fairytale', 'Fairytale'), ('Fantasy', 'Fantasy'), ('Graphic novel', 'Graphic novel'), ('Historical fiction', 'Historical fiction'), ('Horror', 'Horror'), ('Humor', 'Humor'), ('Legend', 'Legend'), ('Magic', 'Magic'), ('Meta-fiction', 'Meta-fiction'), ('Mystery', 'Mystery'), ('Mythology', 'Mythology'), ('Mythopoeia', 'Mythopoeia'), ('Pictures', 'Pictures'), ('Political', 'Political'), ('Realistic', 'Realistic'), ('Romance', 'Romance'), ('Satire', 'Satire'), ('Science fiction', 'Science fiction'), ('Suspense', 'Suspense'), ('Swashbuckler', 'Swashbuckler'), ('Thriller', 'Thriller'), ('Tall tale', 'Tall tale'), ('Western', 'Western'), ('Young adult', 'Young adult')], max_length=100, null=True)),
                ('album', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Album')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='StoryCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('arc', tinymce.models.HTMLField(blank=True, null=True)),
                ('role', models.CharField(blank=True, choices=[('Protagonist', 'Protagonist'), ('Deuteragonist', 'Deuteragonist'), ('Antagonist', 'Antagonist'), ('Love Interest', 'Love Interest'), ('Mentor', 'Mentor'), ('Narrator', 'Narrator'), ('Secondary', 'Secondary Character'), ('Tertiary', 'Tertiary Character'), ('Flat', 'Flat Character')], max_length=100, null=True)),
                ('character', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='characters.Character')),
                ('story', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Story')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='characters',
            field=models.ManyToManyField(blank=True, through='stories.StoryCharacter', to='characters.Character'),
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('goal', tinymce.models.HTMLField(blank=True, null=True)),
                ('emotion', tinymce.models.HTMLField(blank=True, null=True)),
                ('setting', tinymce.models.HTMLField(blank=True, null=True)),
                ('pov', models.CharField(blank=True, max_length=255, null=True)),
                ('action', tinymce.models.HTMLField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(blank=True, default=0)),
                ('chapter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='stories.Chapter')),
                ('characters', models.ManyToManyField(blank=True, related_name='scenes', to='characters.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('setting', tinymce.models.HTMLField(blank=True, null=True)),
                ('ending', tinymce.models.HTMLField(blank=True, null=True)),
                ('beginning', tinymce.models.HTMLField(blank=True, null=True)),
                ('synopsis', tinymce.models.HTMLField(blank=True, null=True)),
                ('antagonist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antagonist_premises', to='stories.StoryCharacter')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='premises', to='accounts.UserProfile')),
                ('protagonist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protagonist_premises', to='stories.StoryCharacter')),
                ('story', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Story')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('exposition', tinymce.models.HTMLField(blank=True, null=True)),
                ('conflict', tinymce.models.HTMLField(blank=True, null=True)),
                ('rising_action', tinymce.models.HTMLField(blank=True, null=True)),
                ('climax', tinymce.models.HTMLField(blank=True, null=True)),
                ('falling_action', tinymce.models.HTMLField(blank=True, null=True)),
                ('resolution', tinymce.models.HTMLField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='accounts.UserProfile')),
                ('story', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Story')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True)),
                ('character', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='characters.Character')),
                ('scene', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='stories.Scene')),
            ],
        ),
        migrations.AddField(
            model_name='act',
            name='story',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='stories.Story'),
        ),
    ]
