# Generated by Django 2.2 on 2019-05-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20190512_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action/Adventure', 'Action/Adventure'), ('Alt-History', 'Alternate History'), ('Anthology', 'Anthology'), ('Children', 'Children'), ('Classic', 'Classic'), ('Comic', 'Comic'), ('Coming-of-age', 'Coming of age'), ('Crime/detective', 'Crime/detective'), ('Drama', 'Drama'), ('Erotic', 'Erotic'), ('Fable', 'Fable'), ('Fan-fiction', 'Fan fiction'), ('Fairytale', 'Fairytale'), ('Fantasy', 'Fantasy'), ('Graphic novel', 'Graphic novel'), ('Historical fiction', 'Historical fiction'), ('Horror', 'Horror'), ('Humor', 'Humor'), ('Legend', 'Legend'), ('Magic', 'Magic'), ('Meta-fiction', 'Meta-fiction'), ('Mystery', 'Mystery'), ('Mythology', 'Mythology'), ('Mythopoeia', 'Mythopoeia'), ('Pictures', 'Pictures'), ('Political', 'Political'), ('Realistic', 'Realistic'), ('Romance', 'Romance'), ('Satire', 'Satire'), ('Science fiction', 'Science fiction'), ('Suspense', 'Suspense'), ('Swashbuckler', 'Swashbuckler'), ('Thriller', 'Thriller'), ('Tall tale', 'Tall tale'), ('Western', 'Western'), ('Young adult', 'Young adult')], max_length=100, null=True),
        ),
    ]
