# Generated by Django 2.2 on 2019-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20190529_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
