# Generated by Django 2.2 on 2019-05-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='author',
        ),
        migrations.RemoveField(
            model_name='premise',
            name='author',
        ),
    ]
