# Generated by Django 2.2 on 2019-05-02 09:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('scenery', tinymce.models.HTMLField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('overview', tinymce.models.HTMLField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('appearance', tinymce.models.HTMLField(blank=True, null=True)),
                ('unique_abilities', tinymce.models.HTMLField(blank=True, null=True)),
                ('intelligence', tinymce.models.HTMLField(blank=True, null=True)),
                ('origins', tinymce.models.HTMLField(blank=True, null=True)),
                ('habitat', tinymce.models.HTMLField(blank=True, null=True)),
                ('ecosystem', tinymce.models.HTMLField(blank=True, null=True)),
                ('diet', tinymce.models.HTMLField(blank=True, null=True)),
                ('predators', tinymce.models.HTMLField(blank=True, null=True)),
                ('defense', tinymce.models.HTMLField(blank=True, null=True)),
                ('extra', tinymce.models.HTMLField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='accounts.UserProfile')),
                ('places', models.ManyToManyField(blank=True, related_name='species', to='worlds.Place')),
                ('world', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='worlds.World')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('span', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='accounts.UserProfile')),
                ('world', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='worlds.World')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('can', tinymce.models.HTMLField(blank=True, null=True)),
                ('cannot', tinymce.models.HTMLField(blank=True, null=True)),
                ('explanation', tinymce.models.HTMLField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.UserProfile')),
                ('world', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='worlds.World')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('weather', tinymce.models.HTMLField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.Place')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='worlds.Season')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='seasons', through='worlds.PlaceSeason', to='worlds.Season'),
        ),
        migrations.AddField(
            model_name='place',
            name='world',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='worlds.World'),
        ),
        migrations.CreateModel(
            name='NaturalPhenomena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_phenomenas', to='accounts.UserProfile')),
                ('world', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_phenomenas', to='worlds.World')),
            ],
        ),
        migrations.CreateModel(
            name='NaturalObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('appearance', tinymce.models.HTMLField(blank=True, null=True)),
                ('history', tinymce.models.HTMLField(blank=True, null=True)),
                ('value', models.CharField(blank=True, choices=[('High', 'High'), ('Average', 'Average'), ('Low', 'Low'), ('None', 'None')], max_length=255, null=True)),
                ('value_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_objects', to='accounts.UserProfile')),
                ('places', models.ManyToManyField(blank=True, related_name='natural_objects', to='worlds.Place')),
                ('world', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_objects', to='worlds.World')),
            ],
        ),
        migrations.CreateModel(
            name='CelestialBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='celestial_bodies', to='accounts.UserProfile')),
                ('world', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='celestial_bodies', to='worlds.World')),
            ],
        ),
    ]
