# Generated by Django 2.2 on 2019-04-16 22:25

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='description',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='can',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='cannot',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='explanation',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='overview',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
