# Generated by Django 2.2 on 2019-04-17 23:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_auto_20190416_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='can',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='cannot',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='explanation',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='overview',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
