# Generated by Django 2.2 on 2019-04-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_auto_20190417_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='can',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='cannot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
