# Generated by Django 2.2 on 2019-04-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0006_auto_20190422_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalobject',
            name='world',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='natural_objects', to='worlds.World'),
            preserve_default=False,
        ),
    ]
