# Generated by Django 2.2 on 2019-04-23 05:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0008_species_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='ecosystem',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
