# Generated by Django 2.2 on 2019-04-24 17:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0012_auto_20190423_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='is_intelligent',
        ),
        migrations.AddField(
            model_name='species',
            name='intelligence',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
