# Generated by Django 2.2 on 2019-04-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0013_auto_20190424_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='place',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='society',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='places',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='societies',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='species',
        ),
        migrations.RemoveField(
            model_name='socialgroup',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='socialgroup',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='socialgroup',
            name='society',
        ),
        migrations.RemoveField(
            model_name='socialgroup',
            name='species',
        ),
        migrations.RemoveField(
            model_name='society',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='society',
            name='places',
        ),
        migrations.RemoveField(
            model_name='society',
            name='species',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='societies',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Infrastructure',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
        migrations.DeleteModel(
            name='SocialGroup',
        ),
        migrations.DeleteModel(
            name='Society',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
