# Generated by Django 2.2 on 2019-04-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0014_auto_20190424_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='background',
            new_name='description',
        ),
    ]
