# Generated by Django 2.2 on 2019-04-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0015_auto_20190426_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='seasons', through='worlds.PlaceSeason', to='worlds.Season'),
        ),
    ]
