# Generated by Django 2.2 on 2019-04-25 05:40

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile_user'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('object_id', models.IntegerField()),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='accounts.UserProfile')),
                ('object_content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='contenttypes.ContentType')),
            ],
        ),
    ]
