# Generated by Django 2.2 on 2019-05-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('histories', '0003_auto_20190426_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='characters.Character'),
        ),
    ]
