# Generated by Django 2.2 on 2019-05-03 09:13

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='celestial_bodies', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('scenery', tinymce.models.HTMLField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('celestial_bodies', models.ManyToManyField(blank=True, related_name='places', to='universes.CelestialBody')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('overview', tinymce.models.HTMLField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universes', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('appearance', tinymce.models.HTMLField(blank=True, null=True)),
                ('unique_abilities', tinymce.models.HTMLField(blank=True, null=True)),
                ('intelligence', tinymce.models.HTMLField(blank=True, null=True)),
                ('origins', tinymce.models.HTMLField(blank=True, null=True)),
                ('habitat', tinymce.models.HTMLField(blank=True, null=True)),
                ('ecosystem', tinymce.models.HTMLField(blank=True, null=True)),
                ('diet', tinymce.models.HTMLField(blank=True, null=True)),
                ('predators', tinymce.models.HTMLField(blank=True, null=True)),
                ('defense', tinymce.models.HTMLField(blank=True, null=True)),
                ('extra', tinymce.models.HTMLField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('celestial_bodies', models.ManyToManyField(blank=True, related_name='species', to='universes.CelestialBody')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='accounts.UserProfile')),
                ('places', models.ManyToManyField(blank=True, related_name='species', to='universes.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('span', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('celestial_bodies', models.ManyToManyField(blank=True, related_name='seasons', to='universes.CelestialBody')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('weather', tinymce.models.HTMLField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universes.Place')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universes.Season')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='places', through='universes.PlaceSeason', to='universes.Season'),
        ),
        migrations.CreateModel(
            name='NaturalPhenomena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('celestial_bodies', models.ManyToManyField(blank=True, related_name='natural_phenomenas', to='universes.CelestialBody')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_phenomenas', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='NaturalObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('appearance', tinymce.models.HTMLField(blank=True, null=True)),
                ('history', tinymce.models.HTMLField(blank=True, null=True)),
                ('value', models.CharField(blank=True, choices=[('High', 'High'), ('Average', 'Average'), ('Low', 'Low'), ('None', 'None')], max_length=255, null=True)),
                ('value_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('celestial_bodies', models.ManyToManyField(blank=True, related_name='natural_objects', to='universes.CelestialBody')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_objects', to='accounts.UserProfile')),
                ('places', models.ManyToManyField(blank=True, related_name='natural_objects', to='universes.Place')),
            ],
        ),
        migrations.CreateModel(
            name='NaturalLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('can', tinymce.models.HTMLField(blank=True, null=True)),
                ('cannot', tinymce.models.HTMLField(blank=True, null=True)),
                ('explanation', tinymce.models.HTMLField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_laws', to='accounts.UserProfile')),
                ('universes', models.ManyToManyField(blank=True, related_name='natural_laws', to='universes.Universe')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('matter_state', models.CharField(blank=True, choices=[('Gas', 'Gas'), ('Liquid', 'Liquid'), ('Solid', 'Solid'), ('Unknown', 'Unknown')], max_length=25, null=True)),
                ('is_metal', models.BooleanField(default=False)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='accounts.UserProfile')),
                ('universes', models.ManyToManyField(blank=True, related_name='elements', to='universes.Universe')),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='accounts.UserProfile')),
                ('elements', models.ManyToManyField(related_name='compounds', to='universes.Element')),
                ('universes', models.ManyToManyField(blank=True, related_name='compounds', to='universes.Universe')),
            ],
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='universes',
            field=models.ManyToManyField(blank=True, related_name='celestial_bodies', to='universes.Universe'),
        ),
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('atomic_number', models.IntegerField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atoms', to='accounts.UserProfile')),
                ('universes', models.ManyToManyField(blank=True, related_name='atoms', to='universes.Universe')),
            ],
        ),
    ]
