# Generated by Django 2.2 on 2019-05-05 04:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_user'),
        ('universes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atom',
            name='atomic_number',
        ),
        migrations.CreateModel(
            name='Particle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('overview', tinymce.models.HTMLField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'Private'), ('Collaborators', 'Collaborators'), ('Group', 'Group'), ('Public', 'Public')], default='Private', max_length=13)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particles', to='accounts.UserProfile')),
                ('universes', models.ManyToManyField(blank=True, related_name='particles', to='universes.Universe')),
            ],
        ),
        migrations.AddField(
            model_name='atom',
            name='particles',
            field=models.ManyToManyField(blank=True, related_name='atoms', to='universes.Particle'),
        ),
    ]
