# Generated by Django 2.2 on 2019-05-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0002_auto_20190504_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particle',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='particles', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='universe',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='universes', to='accounts.UserProfile'),
        ),
    ]
