# Generated by Django 2.2 on 2019-05-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0003_auto_20190505_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='particle',
            old_name='overview',
            new_name='description',
        ),
        migrations.AddField(
            model_name='particle',
            name='composition',
            field=models.ManyToManyField(blank=True, related_name='_particle_composition_+', to='universes.Particle'),
        ),
        migrations.AddField(
            model_name='particle',
            name='is_stable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='particle',
            name='size',
            field=models.CharField(blank=True, choices=[('Subatomic', 'Subatomic'), ('Microscopic', 'Microscopic'), ('Macroscopic', 'Macroscopic')], max_length=11, null=True),
        ),
        migrations.DeleteModel(
            name='Atom',
        ),
    ]
