# Generated by Django 2.2 on 2019-05-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0004_auto_20190507_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compound',
        ),
    ]
