# Generated by Django 2.2 on 2019-04-28 04:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20190426_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='legal',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
