# Generated by Django 2.2 on 2019-04-25 05:40

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('accounts', '0002_userprofile_user'),
        ('worlds', '0014_auto_20190424_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('appearance', tinymce.models.HTMLField(blank=True, null=True)),
                ('utility', tinymce.models.HTMLField(blank=True, null=True)),
                ('origins', tinymce.models.HTMLField(blank=True, null=True)),
                ('extra', tinymce.models.HTMLField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='accounts.UserProfile')),
                ('societies', models.ManyToManyField(blank=True, related_name='technologies', to='communities.Society')),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', tinymce.models.HTMLField(blank=True, null=True)),
                ('appearance', tinymce.models.HTMLField(blank=True, null=True)),
                ('purpose', tinymce.models.HTMLField(blank=True, null=True)),
                ('origins', tinymce.models.HTMLField(blank=True, null=True)),
                ('extra', tinymce.models.HTMLField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='accounts.UserProfile')),
                ('places', models.ManyToManyField(blank=True, null=True, related_name='infrastructures', to='worlds.Place')),
                ('societies', models.ManyToManyField(blank=True, related_name='infrastructures', to='communities.Society')),
            ],
        ),
    ]
