# Generated by Django 2.2 on 2019-04-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iandt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='infrastructures', to='worlds.Place'),
        ),
    ]
